#!/bin/bash

URL=http://faenza-icon-theme.googlecode.com/files/faenza-icon-theme_1.1.tar.gz

# Otherwise, set it up
[ -d ~/.icons ] || mkdir ~/.icons

if [ ! -e ~/.icons/faenza.tgz ]; then
    curl -Lo ~/.icons/faenza.tgz "$URL"
fi

# Extract
if [ ! -d ~/.icons/Faenza ]; then
    tar zxf ~/.icons/faenza.tgz -C ~/.icons/ \
      Faenza \
      Faenza-Dark \
      Faenza-Darker \
      Faenza-Darkest
fi

# Patch
function patch-pidgin() {
    url="http://ubuntuone.com/p/133Z/"
    
    if [ ! -e ~/.icons/faenza-pidgin.zip ]; then
        curl -Lo ~/.icons/faenza-pidgin.zip ${url}
    fi

    mkdir -p ~/.icons/Faenza-Darkest/status/{16,22}

    for size in 16 22; do
        unzip -xj ~/.icons/faenza-pidgin.zip \
          -d ~/.icons/Faenza-Darkest/status/${size} \
          dark/${size}x${size}/status/pidgin\*
    done
}

patch-pidgin
