#!/bin/sh

# Extract archive to current working directory, in path .dotfiles
( base64 -d | tar zxf - ) << EOF
EOF

if [ -d .dotfiles ]; then
    .dotfiles/install $1
    rm -rvf .dotfiles
else
    echo "Error installing"
    exit 1
fi

